name: HTML Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate HTML files
        uses: chrisdarroch/html5-validator-action@v1
        with:
          files: "*.html"
